# -*- coding: utf-8 -*-
"""Task05_CS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S76jDZr66qwnp3Rc_rMA2Yw8sDw3D21U
"""

import sys
!{sys.executable} -m pip install scapy
from scapy.all import rdpcap
from scapy.layers.inet import IP, TCP, UDP, ICMP


def analyze_pcap(file_path):
    print("Loading packets...\n")
    packets = rdpcap(file_path)

    for i, packet in enumerate(packets):
        print(f"Packet #{i+1}")

        if IP in packet:
            print(f"Source IP      : {packet[IP].src}")
            print(f"Destination IP : {packet[IP].dst}")
            print(f"Protocol       : {packet[IP].proto}")
            print(f"Packet Length  : {len(packet)} bytes")

            if TCP in packet:
                print("Layer          : TCP")
                print(f"Source Port    : {packet[TCP].sport}")
                print(f"Destination Port: {packet[TCP].dport}")

            elif UDP in packet:
                print("Layer          : UDP")
                print(f"Source Port    : {packet[UDP].sport}")
                print(f"Destination Port: {packet[UDP].dport}")

            elif ICMP in packet:
                print("Layer          : ICMP")

            print("-" * 50)

        else:
            print("Non-IP Packet")
            print("-" * 50)


def main():
    print("===== Network Packet Analyzer ===")
    file_path = input("Enter path to PCAP file: ")
    analyze_pcap(file_path)


if __name__ == "__main__":
    main()